/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hotfix_NativeHookUtils */

#ifndef _Included_com_example_hotfix_NativeHookUtils
#define _Included_com_example_hotfix_NativeHookUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hotfix_NativeHookUtils
 * Method:    patch
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_example_hotfix_NativeHookUtils_patch
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
